### ISSUE TITLE
my first reaction

### ISSUE THREAD

**Issue by ChrissyNova** [JoranJix/Undressify#1]
Hi, my big issue: Friendlist cannot be turned off. Added 1 person to access list but friendlist stays on. Clicking Friends button multiple times>> not working. 

Other first opinions. Everyone uses this undress hud their own way, for me this new version has some limitations. I like the way it works, same as it did before. But, I used the Avatar for different body types. Like Avatar for Maitreya, one for LaraX, one for Legacy. etc. This meant clothing had to be connected to the avatar. I cannot wear the clothes of the Larax body on the Legacy avatar. Etc..  So this new 'feature' makes the avatar function unworkable for me. 

Will there be more stages as once with db version? There seems to be a 'dead' button click when you have only 2 stages. To redress an item you now have to do a click without a function. 

I miss the 'rape' button ;-)

Those were my first remarks. Thank you for creating great things in sl. x Chrissy

**Comment by JoranJix** [comment]
First of all thank you for your report.

Yes I now see theFriends does not turn off. Will fix it.

On the old system I conducted a survey in the database and many people only used one avatar. That is actually the reason why I did it. 

More stages are not planned yet. But I will check for the dead click. 

As of this moment I dont have the time nor do I have the mindset to work on it because of RL. 

The Rape function will not return. I lost all animations and models for it. Thanks to LL btw... for nothing.
